version: "3"

services:
  atrias-frontend:
    container_name: atrias-dommage-ouvrage-${deployment_environment}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    restart: always
